title: Mi sitio web sencillo
description: p√°gina creada con jekyly y github  page 
remote_theme: remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
